# Batch size to use for training.
batch_size: 32
# Batch size to use for training RotNet
rot_net_batch_size: 8
# Batch size to use for training colorization.
colorization_batch_size: 16

# Learning phases to use for training the model.
learning_phases:
  # The initial learning rate to use for the phase.
  - learning_rate:
      # Initial learning rate value.
      initial: 0.002
