[tool.poetry]
name = "cotton_flower_mot"
version = "0.1.0"
description = "Multi-object tracking for cotton flowers."
authors = ["Daniel Petti <djpetti@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.8"
tensorflow = "^2.4.1"
kedro = {extras = ["matplotlib", "pandas"], version = "^0.17.1"}
pycvat = {git = "git@github.com:UGA-BSAIL/pycvat.git", rev = "a7a0d510"}
pandas = "^1.2.3"
loguru = "^0.5.3"
numpy = ">=1.19.2,<1.20.0"
spektral = "^1.0.5"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-mock = "^3.5.1"
pytest-black = "^0.3.12"
black = "^20.8b1"
isort = "^5.7.0"
pre-commit = "^2.11.0"

[tool.black]
line-length = 79
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.venv
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 79
skip = "('.eggs', '.git', '.venv', 'build', 'dist')"

[tool.kedro]
package_name = "cotton_flower_mot"
project_name = "Cotton Flower MOT"
project_version = "0.17.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
