[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "ultralytics<9.0.0,>=8.0.208",
    "pytest<7.0.0,>=6.2.2",
    "pytest-mock<4.0.0,>=3.5.1",
    "pytest-black<1.0.0,>=0.3.12",
    "black<23.0.0,>=22.3.0",
    "isort<6.0.0,>=5.7.0",
    "pre-commit<3.0.0,>=2.11.0",
    "pytest-snapshot<1.0.0,>=0.5.0",
    "Faker<18.0.0,>=17.6.0",
    "pytest-coverage<1.0,>=0.0",
    "PyYAML<7.0.0,>=6.0.1",
    "pytest-flake8<2.0.0,>=1.0.7",
    "pydot<2.0.0,>=1.4.2",
    "jupyterlab<4.0.0,>=3.4.2",
    "kedro[matplotlib,pandas]<1.0.0,>=0.18.1,<0.19.0",
    "tables==3.9.2",
]

[tool.setuptools.package-data]
myModule = ["*.csv"]

[tool.pdm.build]
includes = []

[[tool.pdm.source]]
name = "nvidia"
url = "https://pypi.nvidia.com"
verify_ssl = true

[project]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
name = "cotton-flower-mot"
version = "2.0.0"
authors = [
    {name = "Daniel Petti", email = "djpetti@gmail.com"},
]
license = {text = "MIT"}
requires-python = "<3.11,>=3.8"
dependencies = [
    "pycvat @ file:///${PROJECT_ROOT}/pycvat",
    "pandas==1.4.3",
    "loguru<1.0.0,>=0.5.3",
    "spektral<2.0.0,>=1.2.0",
    "seaborn<1.0.0,>=0.13.2",
    "matplotlib<4.0.0,>=3.3.4",
    "pydantic<2.0.0,>=1.8.1",
    "scipy<2.0.0,>=1.6.2",
    "opencv-python-headless<5.0.0,>=4.7.0",
    "tenacity<9.0.0,>=8.0.1",
    "opencv-contrib-python-headless<5.0.0,>=4.7.0",
    "tqdm<5.0.0,>=4.64.0",
    "tabulate<1.0.0,>=0.9.0",
    "kalmankit<2.0.0,>=1.7.8",
    "av<12.0.0,>=11.0.0",
    "tensorflow[and-cuda]==2.12; platform_machine == 'x86_64' and python_version < '3.9'",
    "tensorflow[and-cuda]==2.15; platform_machine == 'x86_64' and python_version >= '3.9'",
    "tensorflow[and-cuda] @ https://developer.download.nvidia.com/compute/redist/jp/v512/tensorflow/tensorflow-2.12.0+nv23.06-cp38-cp38-linux_aarch64.whl ; platform_machine == 'aarch64'",
    "tensorflow-serving-api==2.12.1",
]

[tool.pdm.resolution.overrides]
# The version kedro wants fails to build.
tables = "3.9.2"

[tool.black]
line-length = 79
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.venv
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 79
skip = "('.eggs', '.git', '.venv', 'build', 'dist')"

[tool.kedro]
package_name = "cotton_flower_mot"
project_name = "Cotton Flower MOT"
kedro_init_version = "0.18.1"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
