# Shape of the input detection crops, in the form of height, width, channels.
image_input_shape: [100, 100, 3]
# Number of appearance features to generate.
num_appearance_features: 256
# Number of GCN output channels to use.
num_gcn_channels: 256
# Sinkhorn normalization Lambda value.
sinkhorn_lambda: 10.0
# How much to weight positive samples in the loss.
positive_sample_weight: 3.0

# Batch size to use for training.
batch_size: 16

# Tensorboard parameters.
# Log directory.
tensorboard_output_dir: ${log_dir}/tensorboard
# Period at which to write histograms, in epochs.
histogram_period: 2
# Period at which to write metrics, in batches.
update_period: 100

# Whether to enable debugging checks for NaN and infinity. This
# is very useful when trying to debug numerical issues, but it
# slows down training a lot.
enable_numeric_checks: false

# Learning phases to use for training the model.
learning_phases:
  # The initial learning rate to use for the phase.
  - learning_rate:
      # Initial learning rate value.
      initial: 0.01
      # Specify that we want to decay over time.
      decay: true
      # Number of steps to decay over.
      # (210 steps per epoch)
      decay_steps: 630
      # Used to derive the number of iterations in the i-th period.
      t_mul: 2.0
      # Used to derive the initial learning rate of the i-th period.
      m_mul: 1.0
      # Minimum learning rate to hit.
      min_learning_rate: 0.000001
    # The momentum to use for the phase.
    momentum: 0.9
    # Number of epochs to train for in this phase.
    num_epochs: 45
