# Shape of the input detection crops, in the form of height, width, channels.
image_input_shape: [100, 100, 3]
# Shape of the raw video frames, in the form of height, width, channels.
frame_input_shape: [1080, 1920, 3]
# Shape of the input to the detection model.
detection_model_input_shape: [540, 960, 3]
# Shape of the input to the RotNet model.
rot_net_input_shape: [360, 360, 3]
# Shape of the input to the colorization model.
colorization_input_shape: [270, 480, 1]
# Shape of the output from the colorization model. The last dimension
# is the number of bins in the histograms.
colorization_output_shape: [72, 120, 32]
# Size to use for the ROI pooling operation when downsampling the detector
# features to appearance features.
roi_pooling_size: 7
# Number of appearance features to generate.
num_appearance_features: 128
# Number of node features to use in the CensNet layers.
num_node_features: 128
# Number of edge features to use in the CensNet layers.
num_edge_features: 128
# Sinkhorn normalization Lambda value.
sinkhorn_lambda: 10.0
# Number of reduction stages to include in the detection model.
num_reduction_stages: 2
# Sigma to use for density maps.
detection_sigma: 3
# Average size of detections, in fractions of a frame, in the form (width, height).
nominal_detection_size: [0.052, 0.093]
